// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ShawkanyDb;
using ShawkanyDb.Models.Model;
using System;

namespace ShawkanyDb.Migrations
{
    [DbContext(typeof(ShawkanyDbContext))]
    partial class MirbatZadaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShawkanyDb.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CategoryID");

                    b.Property<string>("Category1")
                        .HasColumnName("Category")
                        .HasMaxLength(50);

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShawkanyDb.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CompanyID");

                    b.Property<string>("Company1")
                        .HasColumnName("Company")
                        .HasMaxLength(50);

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("ShawkanyDb.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CountryID");

                    b.Property<string>("Country1")
                        .HasColumnName("Country")
                        .HasMaxLength(50);

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("ShawkanyDb.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .HasColumnName("CurrencyID");

                    b.Property<string>("Currency1")
                        .HasColumnName("Currency")
                        .HasMaxLength(50);

                    b.HasKey("CurrencyId");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("ShawkanyDb.CurrencyExchangeRate", b =>
                {
                    b.Property<int>("CurrencyExchangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CurrencyExchangeID");

                    b.Property<double?>("AfghaniRateToRupe");

                    b.Property<double?>("AfhaniRateToDoller");

                    b.HasKey("CurrencyExchangeId");

                    b.ToTable("CurrencyExchangeRate");
                });

            modelBuilder.Entity("ShawkanyDb.Deal", b =>
                {
                    b.Property<int>("DealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DealID");

                    b.Property<double?>("Credit");

                    b.Property<int?>("CurrencyId")
                        .HasColumnName("CurrencyID");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DealTypeId")
                        .HasColumnName("DealTypeID");

                    b.Property<int?>("DealerId")
                        .HasColumnName("DealerID");

                    b.Property<double?>("Debit");

                    b.Property<string>("Detail");

                    b.Property<int?>("EmployeeId")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Loan")
                        .HasMaxLength(5);

                    b.HasKey("DealId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DealTypeId");

                    b.HasIndex("DealerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Deal");
                });

            modelBuilder.Entity("ShawkanyDb.DealerType", b =>
                {
                    b.Property<int>("DealerTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DealerTypeID");

                    b.Property<string>("Dealer")
                        .HasMaxLength(50);

                    b.HasKey("DealerTypeId");

                    b.ToTable("DealerType");
                });

            modelBuilder.Entity("ShawkanyDb.Dealler", b =>
                {
                    b.Property<int>("DealerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DealerID");

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<string>("DealerName")
                        .HasMaxLength(50);

                    b.Property<int?>("DealerTypeId")
                        .HasColumnName("DealerTypeID");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasMaxLength(15);

                    b.HasKey("DealerId");

                    b.HasIndex("DealerTypeId");

                    b.ToTable("Dealler");
                });

            modelBuilder.Entity("ShawkanyDb.DealType", b =>
                {
                    b.Property<int>("DealTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DealTypeID");

                    b.Property<string>("DealType1")
                        .HasColumnName("DealType")
                        .HasMaxLength(50);

                    b.HasKey("DealTypeId");

                    b.ToTable("DealType");
                });

            modelBuilder.Entity("ShawkanyDb.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Address")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("Image")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<int>("Salary");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ShawkanyDb.Expence", b =>
                {
                    b.Property<int>("ExpenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ExpenceID");

                    b.Property<string>("Detail")
                        .HasMaxLength(200);

                    b.Property<int?>("EmployeeId")
                        .HasColumnName("EmployeeID");

                    b.Property<int>("ExpenceAmount");

                    b.Property<DateTime?>("ExpenceDate")
                        .HasColumnType("date");

                    b.Property<int?>("ExpenceTypeId")
                        .HasColumnName("ExpenceTypeID");

                    b.HasKey("ExpenceId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ExpenceTypeId");

                    b.ToTable("Expence");
                });

            modelBuilder.Entity("ShawkanyDb.ExpenceType", b =>
                {
                    b.Property<int>("ExpenceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ExpenceTypeID");

                    b.Property<string>("ExpenceType1")
                        .HasColumnName("ExpenceType")
                        .HasMaxLength(50);

                    b.HasKey("ExpenceTypeId");

                    b.ToTable("ExpenceType");
                });

            modelBuilder.Entity("ShawkanyDb.ExpiredItem", b =>
                {
                    b.Property<int>("ExpireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ExpireID");

                    b.Property<string>("Company")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasMaxLength(50);

                    b.Property<string>("Currency")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("date");

                    b.Property<string>("Item")
                        .HasMaxLength(50);

                    b.Property<string>("LatineName")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("date");

                    b.Property<double?>("PurchasePrice");

                    b.Property<int?>("Quantity");

                    b.Property<double?>("SalePrice");

                    b.HasKey("ExpireId");

                    b.ToTable("ExpiredItem");
                });

            modelBuilder.Entity("ShawkanyDb.ExpiredItemsDueToDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int?>("Days");

                    b.HasKey("Id");

                    b.ToTable("ExpiredItemsDueToDays");
                });

            modelBuilder.Entity("ShawkanyDb.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ItemID");

                    b.Property<int?>("CategoryId")
                        .HasColumnName("CategoryID");

                    b.Property<int?>("CompanyId")
                        .HasColumnName("CompanyID");

                    b.Property<int?>("CountryId")
                        .HasColumnName("CountryID");

                    b.Property<string>("LatinName")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("OldPrice");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("ShawkanyDb.Item2", b =>
                {
                    b.Property<int>("Item2Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Item2ID");

                    b.Property<int?>("AmountInPackage");

                    b.Property<int?>("CurrencyId")
                        .HasColumnName("CurrencyID");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ItemId")
                        .HasColumnName("ItemID");

                    b.Property<DateTime?>("ManufictureDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PurchasePrice");

                    b.Property<int?>("SalePrice");

                    b.Property<int?>("TotalQuantity");

                    b.Property<int?>("UnitId")
                        .HasColumnName("UnitID");

                    b.HasKey("Item2Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UnitId");

                    b.ToTable("Item2");
                });

            modelBuilder.Entity("ShawkanyDb.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NoteID");

                    b.Property<int?>("EmpoyeeId")
                        .HasColumnName("EmpoyeeID");

                    b.Property<string>("Note1")
                        .HasColumnName("Note");

                    b.Property<string>("NoteStatus")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("RemindDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime");

                    b.HasKey("NoteId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ShawkanyDb.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PurchaseID");

                    b.Property<int?>("AmountInPackage");

                    b.Property<string>("BillNo")
                        .HasColumnName("Bill_No")
                        .HasMaxLength(50);

                    b.Property<int?>("CompanyId")
                        .HasColumnName("CompanyID");

                    b.Property<int?>("CountryId")
                        .HasColumnName("CountryID");

                    b.Property<int?>("CurrencyId")
                        .HasColumnName("CurrencyID");

                    b.Property<int?>("DealerId")
                        .HasColumnName("DealerID");

                    b.Property<int?>("EmployeeId")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ItemId")
                        .HasColumnName("ItemID");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<double?>("PurchasePrice");

                    b.Property<string>("PurchaseState")
                        .HasMaxLength(50);

                    b.Property<int?>("Quantity");

                    b.Property<double?>("SalePrice");

                    b.Property<int?>("StockId")
                        .HasColumnName("StockID");

                    b.Property<int?>("UnitId")
                        .HasColumnName("UnitID");

                    b.HasKey("PurchaseId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DealerId")
                        .HasName("IX_Purchase_CorporationID");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ItemId");

                    b.HasIndex("StockId");

                    b.HasIndex("UnitId");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("ShawkanyDb.SalaryPayment", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SalaryID");

                    b.Property<int?>("EmployeeId")
                        .HasColumnName("EmployeeID");

                    b.Property<int?>("PaidAmount");

                    b.Property<int?>("PaidBy");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("date");

                    b.HasKey("SalaryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PaidBy");

                    b.ToTable("SalaryPayment");
                });

            modelBuilder.Entity("ShawkanyDb.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SaleID");

                    b.Property<int?>("AmountInPackage");

                    b.Property<string>("BillNo")
                        .HasColumnName("Bill_No")
                        .HasMaxLength(50);

                    b.Property<int?>("CompanyId")
                        .HasColumnName("CompanyID");

                    b.Property<int?>("CountryId")
                        .HasColumnName("CountryID");

                    b.Property<int?>("CurrencyId")
                        .HasColumnName("CurrencyID");

                    b.Property<int?>("DealerId")
                        .HasColumnName("DealerID");

                    b.Property<double?>("Discount");

                    b.Property<int?>("EmployeeId")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ItemId")
                        .HasColumnName("ItemID");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(200);

                    b.Property<double?>("PurchasePrice");

                    b.Property<int?>("Quantity");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("date");

                    b.Property<double?>("SalePrice");

                    b.Property<string>("SaleState")
                        .HasMaxLength(50);

                    b.Property<string>("SaleType")
                        .HasMaxLength(50);

                    b.Property<int?>("StockId")
                        .HasColumnName("StockID");

                    b.Property<string>("TempCustomerName")
                        .HasColumnName("tempCustomerName")
                        .HasMaxLength(50);

                    b.Property<int?>("UnitId")
                        .HasColumnName("UnitID");

                    b.HasKey("SaleId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DealerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ItemId");

                    b.HasIndex("StockId");

                    b.HasIndex("UnitId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("ShawkanyDb.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StockID");

                    b.Property<string>("Stock1")
                        .HasColumnName("Stock")
                        .HasMaxLength(50);

                    b.HasKey("StockId");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("ShawkanyDb.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UnitID");

                    b.Property<string>("Unit1")
                        .HasColumnName("Unit")
                        .HasMaxLength(50);

                    b.HasKey("UnitId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("ShawkanyDb.UserLoginDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("LoginDate");

                    b.Property<DateTime?>("LogoutDate");

                    b.Property<string>("UserId")
                        .HasMaxLength(450);

                    b.HasKey("DetailId");

                    b.ToTable("UserLoginDetail");
                });

            modelBuilder.Entity("ShawkanyDb.Deal", b =>
                {
                    b.HasOne("ShawkanyDb.Currency", "Currency")
                        .WithMany("Deal")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK_Deal_Currency");

                    b.HasOne("ShawkanyDb.DealType", "DealType")
                        .WithMany("Deal")
                        .HasForeignKey("DealTypeId")
                        .HasConstraintName("FK_Deal_DealType");

                    b.HasOne("ShawkanyDb.Dealler", "Dealer")
                        .WithMany("Deal")
                        .HasForeignKey("DealerId")
                        .HasConstraintName("FK_Deal_Dealler");

                    b.HasOne("ShawkanyDb.Employee", "Employee")
                        .WithMany("Deal")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Deal_Employee");
                });

            modelBuilder.Entity("ShawkanyDb.Dealler", b =>
                {
                    b.HasOne("ShawkanyDb.DealerType", "DealerType")
                        .WithMany("Dealler")
                        .HasForeignKey("DealerTypeId")
                        .HasConstraintName("FK_Dealler_DealerType");
                });

            modelBuilder.Entity("ShawkanyDb.Expence", b =>
                {
                    b.HasOne("ShawkanyDb.Employee", "Employee")
                        .WithMany("Expence")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Expence_Employee");

                    b.HasOne("ShawkanyDb.ExpenceType", "ExpenceType")
                        .WithMany("Expence")
                        .HasForeignKey("ExpenceTypeId")
                        .HasConstraintName("FK_Expence_ExpenceType");
                });

            modelBuilder.Entity("ShawkanyDb.Item", b =>
                {
                    b.HasOne("ShawkanyDb.Category", "Category")
                        .WithMany("Item")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Item_Category");

                    b.HasOne("ShawkanyDb.Company", "Company")
                        .WithMany("Item")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_Item_Company");

                    b.HasOne("ShawkanyDb.Country", "Country")
                        .WithMany("Item")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Item_Country");
                });

            modelBuilder.Entity("ShawkanyDb.Item2", b =>
                {
                    b.HasOne("ShawkanyDb.Currency", "Currency")
                        .WithMany("Item2")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK_Item2_Currency");

                    b.HasOne("ShawkanyDb.Item", "Item")
                        .WithMany("Item2")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_Item2_Item");

                    b.HasOne("ShawkanyDb.Unit", "Unit")
                        .WithMany("Item2")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("FK_Item2_Unit");
                });

            modelBuilder.Entity("ShawkanyDb.Purchase", b =>
                {
                    b.HasOne("ShawkanyDb.Company", "Company")
                        .WithMany("Purchase")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_Purchase_Company");

                    b.HasOne("ShawkanyDb.Country", "Country")
                        .WithMany("Purchase")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Purchase_Country");

                    b.HasOne("ShawkanyDb.Currency", "Currency")
                        .WithMany("Purchase")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK_Purchase_Currency");

                    b.HasOne("ShawkanyDb.Dealler", "Dealer")
                        .WithMany("Purchase")
                        .HasForeignKey("DealerId")
                        .HasConstraintName("FK_Purchase_Dealler");

                    b.HasOne("ShawkanyDb.Employee", "Employee")
                        .WithMany("Purchase")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Purchase_Employee");

                    b.HasOne("ShawkanyDb.Item", "Item")
                        .WithMany("Purchase")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_Purchase_Item");

                    b.HasOne("ShawkanyDb.Stock", "Stock")
                        .WithMany("Purchase")
                        .HasForeignKey("StockId")
                        .HasConstraintName("FK_Purchase_Stock");

                    b.HasOne("ShawkanyDb.Unit", "Unit")
                        .WithMany("Purchase")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("FK_Purchase_Unit");
                });

            modelBuilder.Entity("ShawkanyDb.SalaryPayment", b =>
                {
                    b.HasOne("ShawkanyDb.Employee", "Employee")
                        .WithMany("SalaryPaymentEmployee")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Salary_Employee")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShawkanyDb.Employee", "PaidByNavigation")
                        .WithMany("SalaryPaymentPaidByNavigation")
                        .HasForeignKey("PaidBy")
                        .HasConstraintName("FK_SalaryPayment_Employee");
                });

            modelBuilder.Entity("ShawkanyDb.Sale", b =>
                {
                    b.HasOne("ShawkanyDb.Company", "Company")
                        .WithMany("Sale")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_Sale_Company");

                    b.HasOne("ShawkanyDb.Country", "Country")
                        .WithMany("Sale")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Sale_Country");

                    b.HasOne("ShawkanyDb.Currency", "Currency")
                        .WithMany("Sale")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK_Sale_Currency");

                    b.HasOne("ShawkanyDb.Dealler", "Dealer")
                        .WithMany("Sale")
                        .HasForeignKey("DealerId")
                        .HasConstraintName("FK_Sale_Dealler1");

                    b.HasOne("ShawkanyDb.Employee", "Employee")
                        .WithMany("Sale")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_Sale_Employee");

                    b.HasOne("ShawkanyDb.Item", "Item")
                        .WithMany("Sale")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_Sale_Item");

                    b.HasOne("ShawkanyDb.Stock", "Stock")
                        .WithMany("Sale")
                        .HasForeignKey("StockId")
                        .HasConstraintName("FK_Sale_Stock");

                    b.HasOne("ShawkanyDb.Unit", "Unit")
                        .WithMany("Sale")
                        .HasForeignKey("UnitId")
                        .HasConstraintName("FK_Sale_Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
